#python

###### GLOBAL VARIABLES HERE ######
base = None
motor = None 
arm = None
pendulum = None
U = None
x1 = None
x2 = None
x3 = None
x4 = None
# You can add variables here 
# as required by your implementation.
###################################

def sysCall_init():
    global base
    base = sim.getObjectHandle('Base_C')
    global arm
    arm = sim.getObjectHandle('Arm_C')
    global pendulum
    pendulum = sim.getObjectHandle('Pendulum_C')
    global motor
    motor = sim.getObjectHandle('Motor_C')
    global elbow
    elbow = sim.getObjectHandle('Elbow_C')
    

    
    # do some initialization here
    # This function will be executed once when the simulation starts
    
    ####### ADD YOUR CODE HERE ######
    # Hint: Initialize the scene objects which you will require 
    #       Initialize algorithm related variables here
    
    #################################
    pass

def sysCall_actuation():
    # put your actuation code here
    # This function will be executed at each simulation time step

    ####### ADD YOUR CODE HERE ######
    # Hint: Use the error feedback and apply control algorithm here
    #       Provide the resulting actuation as input to the actuator joint
    
    # Example psuedo code:
    
    
  
    x1, x2, x3, x4 = sysCall_sensing()
    
    k = [0.0001,   -2.2506,    0.1000,    -1.15723]      # These gains will be generated by control algorithm. For ex: LQR, PID, etc.
    U = -k[0]*x1 +k[1]*x2 -k[2]*x3 +k[3]*x4
    
    
    sim.setJointTargetVelocity(motor, U)

 

    
    #################################
    pass

def sysCall_sensing():
    
    # put your sensing code here
    # This function will be executed at each simulation time step
    x1 = 0 - sim.getJointPosition(motor)
    x2 = 0 - sim.getJointVelocity(motor)
    x3 = 0 - sim.getJointPosition(elbow)
    x4 = 0 - sim.getJointVelocity(elbow)
    
    
    ####### ADD YOUR CODE HERE ######
    # Hint: Take feedback here & do the error calculation
    
    #################################
    return x1, x2, x3, x4
    pass
    

def sysCall_cleanup():
    # do some clean-up here
    # This function will be executed when the simulation ends
    

    ####### ADD YOUR CODE HERE ######
    # Any cleanup (if required) to take the scene back to it's original state after simulation
    # It helps in case simulation fails in an unwanted state.
    #################################
    pass

# See the user manual or the available code snippets for additional callback functions and details

